version: '3'

services:
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/usr/scr/app/static
    ports:
      - 80:80
    depends_on:
      - web
  web:
    build: . 
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/usr/src/app/static
      - ./:/usr/src/app/
    ports:
      - 8000:8000
volumes:
  static_volume: