# Generated by Django 4.1.13 on 2024-03-18 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tour_tmap',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('Name', models.CharField(db_column='Name', max_length=255)),
                ('Address', models.CharField(db_column='Address', max_length=255)),
                ('Latitude', models.FloatField(db_column='Latitude')),
                ('Longitude', models.FloatField(db_column='Longitude')),
                ('Tel', models.CharField(db_column='Tel', max_length=255)),
                ('Image_URL', models.URLField(db_column='Image_URL')),
            ],
        ),
    ]
