# Generated by Django 4.1.13 on 2024-03-11 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ezocr', '0002_remove_ezocrresult_result_text_ezocrresult_context_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ezocrresult',
            name='answer',
            field=models.CharField(default='답변해주세요', max_length=255),
        ),
        migrations.AlterField(
            model_name='ezocrresult',
            name='context',
            field=models.CharField(default='입력해주세요', max_length=255),
        ),
    ]
