# Generated by Django 4.1.13 on 2024-03-11 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ezocr', '0003_ezocrresult_answer_alter_ezocrresult_context'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ezocrresult',
            name='answer',
            field=models.TextField(default='답변해주세요'),
        ),
        migrations.AlterField(
            model_name='ezocrresult',
            name='context',
            field=models.TextField(default='입력해주세요'),
        ),
        migrations.AlterField(
            model_name='ezocrresult',
            name='question',
            field=models.TextField(default='이미지를 넣어주세요'),
        ),
    ]
