# Generated by Django 5.0.1 on 2024-02-21 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='ProfileForm',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
