# Generated by Django 4.1.13 on 2024-03-19 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='profile',
        #     name='is_first',
        # ),
    ]
