# Generated by Django 3.1.1 on 2024-02-26 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_profile_address_alter_profile_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_first',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(choices=[(None, '선택'), ('서울', '서울'), ('인천', '인천')], max_length=50, verbose_name='주소'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
