# Generated by Django 3.1.1 on 2024-02-26 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_auto_20240226_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(choices=[(None, '선택'), ('서울', '서울'), ('인천', '인천')], max_length=50, verbose_name='주소'),
        ),
    ]
