version: '3'
services:
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/usr/src/app/static
    ports:
      - 80:80
    depends_on:
      - web1
      - web2
      - web3
    networks:
      - backend
  web1:
    build: .
    command: gunicorn mysite.wsgi:application --bind 0.0.0.0:8001
    volumes:
      - static_volume:/usr/src/app/static
      - ./:/usr/src/app/
    expose:
      - "8001"
    networks:
      - backend
  web2:
    build: .
    command: gunicorn mysite.wsgi:application --bind 0.0.0.0:8002
    volumes:
      - static_volume:/usr/src/app/static
      - ./:/usr/src/app/
    expose:
      - "8002"
    networks:
      - backend
  web3:
    build: .
    command: gunicorn mysite.wsgi:application --bind 0.0.0.0:8003
    volumes:
      - static_volume:/usr/src/app/static
      - ./:/usr/src/app/
    expose:
      - "8003"
    networks:
      - backend
  rabbitmq:
    image: "rabbitmq:3.7.14-management-alpine"
    environment:
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - backend
  redis:
    container_name: redis_service
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - .:/code
  celery_worker:
    build: .
    command: celery -A mysite worker --loglevel=info
    volumes:
      - static_volume:/usr/src/app/static
      - ./:/usr/src/app/
    networks:
      - backend
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq
    depends_on:
      - rabbitmq
  celery_beat:
    build: .
    command: celery -A mysite beat --loglevel=info
    volumes:
      - static_volume:/usr/src/app/static
      - ./:/usr/src/app/
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq
    networks:
      - backend
    depends_on:
      - rabbitmq
  flower:
    image: mher/flower
    environment:
      - CELERY_BROKER_URL=pyamqp://guest:guest@rabbitmq
    ports:
      - "5555:5555"
    networks:
      - backend
networks:
  backend:
    driver: bridge
volumes:
  static_volume: