# Generated by Django 4.1.13 on 2024-03-18 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='tour_kakao',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('Name', models.CharField(db_column='Name', max_length=255)),
                ('Address', models.CharField(db_column='Address', max_length=255)),
                ('Latitude', models.FloatField(db_column='Latitude')),
                ('Longitude', models.FloatField(db_column='Longitude')),
                ('Tel', models.CharField(db_column='Tel', max_length=255)),
                ('Image_URL', models.URLField(db_column='Image_URL')),
                ('Tag', models.TextField(db_column='Tag', default='')),
                ('Hits', models.IntegerField(db_column='Hits', default=0)),
                ('rec1', models.IntegerField(db_column='rec1', default=0)),
                ('rec2', models.IntegerField(db_column='rec2', default=0)),
                ('rec3', models.IntegerField(db_column='rec3', default=0)),
                ('like', models.ManyToManyField(related_name='like_tour_kakao', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='tour_comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(db_column='Comment')),
                ('create_date', models.DateTimeField()),
                ('modify_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_tour_comment', to=settings.AUTH_USER_MODEL)),
                ('comment_like', models.ManyToManyField(related_name='like_tour_comment', to=settings.AUTH_USER_MODEL)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kakaoapi.tour_kakao')),
            ],
        ),
    ]
