# Generated by Django 4.1.13 on 2024-03-06 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakaoapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour_kakao',
            name='Tel',
            field=models.CharField(db_column='Tel', max_length=255),
        ),
    ]
