# Generated by Django 4.1.13 on 2024-03-11 22:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kakaoapi', '0002_alter_tour_kakao_tel'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour_kakao',
            name='Hits',
            field=models.FloatField(db_column='Hits', default=0),
        ),
        migrations.AddField(
            model_name='tour_kakao',
            name='Tag',
            field=models.CharField(db_column='Tag', default='default_tag_value', max_length=255),
        ),
        migrations.AddField(
            model_name='tour_kakao',
            name='embedding',
            field=models.JSONField(db_column='embedding', default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tour_kakao',
            name='like',
            field=models.ManyToManyField(related_name='like_tour_kakao', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tour_kakao',
            name='rec1',
            field=models.IntegerField(db_column='rec1', default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tour_kakao',
            name='rec2',
            field=models.IntegerField(db_column='rec2', default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tour_kakao',
            name='rec3',
            field=models.IntegerField(db_column='rec3', default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tour_kakao',
            name='tag_embedding',
            field=models.JSONField(db_column='tag_embedding', default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tour_kakao',
            name='id',
            field=models.IntegerField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='tour_comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(db_column='Comment')),
                ('comment_like', models.IntegerField(db_column='Comment_Like', default=0)),
                ('create_date', models.DateTimeField()),
                ('modify_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_tour_comment', to=settings.AUTH_USER_MODEL)),
                ('like', models.ManyToManyField(related_name='like_tour_comment', to=settings.AUTH_USER_MODEL)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kakaoapi.tour_kakao')),
            ],
        ),
    ]
