# Generated by Django 4.1.13 on 2024-03-12 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakaoapi', '0002_remove_tour_comment_like_and_more'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='tour_kakao',
        #     name='Hits',
        #     field=models.IntegerField(db_column='Hits', default=0),
        # ),
        # migrations.AddField(
        #     model_name='tour_kakao',
        #     name='Tag',
        #     field=models.TextField(db_column='Tag', default=''),
        # ),
        # migrations.AddField(
        #     model_name='tour_kakao',
        #     name='rec1',
        #     field=models.IntegerField(db_column='rec1', default=0),
        # ),
        # migrations.AddField(
        #     model_name='tour_kakao',
        #     name='rec2',
        #     field=models.IntegerField(db_column='rec2', default=0),
        # ),
        # migrations.AddField(
        #     model_name='tour_kakao',
        #     name='rec3',
        #     field=models.IntegerField(db_column='rec3', default=0),
        # ),
    ]
