# Generated by Django 4.1.13 on 2024-03-11 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kakaoapi', '0003_tour_kakao_hits_tour_kakao_tag_tour_kakao_embedding_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour_kakao',
            name='embedding',
        ),
        migrations.RemoveField(
            model_name='tour_kakao',
            name='tag_embedding',
        ),
    ]
