# Generated by Django 4.1.13 on 2024-03-12 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kakaoapi', '0003_tour_kakao_hits_tour_kakao_tag_tour_kakao_rec1_and_more'),
        ('kakaoapi', '0003_tour_kakao_like_tour_comment'),
    ]

    operations = [
    ]
