# Generated by Django 4.1.13 on 2024-03-11 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakaoapi', '0004_remove_tour_kakao_embedding_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour_kakao',
            name='Hits',
            field=models.IntegerField(db_column='Hits', default=0),
        ),
    ]
