# Generated by Django 4.1.13 on 2024-03-11 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakaoapi', '0005_alter_tour_kakao_hits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour_kakao',
            name='Tag',
            field=models.TextField(db_column='Tag'),
        ),
    ]
