# Generated by Django 4.1.13 on 2024-03-12 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakaoapi', '0007_tour_kakao_hits_tour_kakao_tag_tour_kakao_rec1_and_more'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='tour_kakao',
        #     name='Hits',
        #     field=models.IntegerField(db_column='Hits', default=0),
        # ),
        # migrations.AddField(
        #     model_name='tour_kakao',
        #     name='Tag',
        #     field=models.TextField(db_column='Tag', default=''),
        # ),
        # migrations.AddField(
        #     model_name='tour_kakao',
        #     name='rec1',
        #     field=models.IntegerField(db_column='rec1', default=0),
        # ),
        # migrations.AddField(
        #     model_name='tour_kakao',
        #     name='rec2',
        #     field=models.IntegerField(db_column='rec2', default=0),
        # ),
        # migrations.AddField(
        #     model_name='tour_kakao',
        #     name='rec3',
        #     field=models.IntegerField(db_column='rec3', default=0),
        # ),
    ]
