# Generated by Django 4.1.13 on 2024-03-12 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kakaoapi', '0009_tour_kakao_hits_tour_kakao_tag_tour_kakao_rec1_and_more'),
    ]

    operations = [
    #     migrations.RemoveField(
    #         model_name='tour_kakao',
    #         name='Hits',
    #     ),
    #     migrations.RemoveField(
    #         model_name='tour_kakao',
    #         name='rec1',
    #     ),
    #     migrations.RemoveField(
    #         model_name='tour_kakao',
    #         name='rec2',
    #     ),
    #     migrations.RemoveField(
    #         model_name='tour_kakao',
    #         name='rec3',
    #     ),
    ]
