# Generated by Django 4.1.13 on 2024-03-12 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakaoapi', '0010_remove_tour_kakao_hits_remove_tour_kakao_rec1_and_more'),
    ]

    operations = [
    #     migrations.AddField(
    #         model_name='tour_kakao',
    #         name='Tag',
    #         field=models.TextField(db_column='Tag', default=''),
    #     ),
    ]
